# Generated by Django 6.0.7 on 2026-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='translationcache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='translationcache',
            name='language',
            field=models.CharField(choices=[('hindi', 'Hindi'), ('hinglish', 'Hinglish')], default='hindi', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='translationcache',
            unique_together={('book', 'page_number', 'language')},
        ),
    ]
