# Generated by Django 6.0.7 on 2026-07-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0002_alter_translationcache_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationcache",
            name="summary_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
