# Generated by Django 6.0.7 on 2026-07-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('user_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
